name            = "core-omakasui-org"
main            = "worker.js"
compatibility_date = "2025-12-01"
workers_dev     = false

[[routes]]
pattern         = "core.omakasui.org/*"
zone_name       = "omakasui.org"
