#!/usr/bin/env bash
# Realign index and frozen legacy metadata with the published release assets.
# Usage: resync-assets.sh [--dry-run] [--repo owner/repo]
# Legacy suites that were rewritten are exported as legacy_suites in GITHUB_OUTPUT.

set -euo pipefail

REPO="omakasui/build-apt-omakasui" DRY_RUN=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 1 ;;
  esac
done
[[ -f index/packages.tsv ]] || { echo "ERROR: index/packages.tsv not found"; exit 1; }

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/debs" "$WORK/stanzas"

# Collect every published reference as "tag file size sha256".
awk '{ n=split($6,u,"/"); print u[n-1], u[n], $7, $10 }' index/packages.tsv > "$WORK/refs"
for f in dists/*/main/binary-*/Packages; do
  [[ -f "$f" ]] || continue
  awk '/^Filename:/{ n=split($2,u,"/") } /^Size:/{ s=$2 } /^SHA256:/{ print u[n-1], u[n], s, $2 }' "$f" >> "$WORK/refs"
done
sort -u -o "$WORK/refs" "$WORK/refs"

for tag in $(awk '{print $1}' "$WORK/refs" | sort -u); do
  gh api "repos/${REPO}/releases/tags/${tag}" \
    --jq ".assets[] | \"${tag} \(.name) \(.size) \(.digest // \"\" | sub(\"^sha256:\"; \"\"))\"" \
    >> "$WORK/assets" 2>/dev/null || echo "WARNING: release ${tag} not found" >&2
done
touch "$WORK/assets"

# Refetch every asset that no longer matches its published metadata.
awk 'NR==FNR { size[$1" "$2]=$3; sha[$1" "$2]=$4; next }
     { k=$1" "$2
       if (!(k in size)) { print "MISSING", k; next }
       if (size[k]!=$3 || (sha[k]!="" && sha[k]!=$4)) print "STALE", k }' \
  "$WORK/assets" "$WORK/refs" | sort -u > "$WORK/drift"

missing=$(grep -c '^MISSING' "$WORK/drift" || true)
grep '^MISSING' "$WORK/drift" | sed 's/^/ERROR: no release asset for /' >&2 || true
if ! grep -q '^STALE' "$WORK/drift"; then
  echo "No stale metadata found."
  [[ -z "${GITHUB_OUTPUT:-}" ]] || echo "legacy_suites=" >> "$GITHUB_OUTPUT"
  exit $(( missing > 0 ))
fi

: > "$WORK/fixes"
while read -r _ tag file; do
  echo "Stale: ${tag}/${file}"
  gh release download "$tag" --repo "$REPO" --pattern "$file" --dir "$WORK/debs" --clobber
  deb="$WORK/debs/$file"
  control=$(dpkg-deb --field "$deb")
  size=$(wc -c < "$deb")
  md5=$(md5sum "$deb" | cut -d' ' -f1)
  sha1=$(sha1sum "$deb" | cut -d' ' -f1)
  sha256=$(sha256sum "$deb" | cut -d' ' -f1)
  printf '%s %s %s %s %s %s %s\n' "$tag" "$file" "$size" "$md5" "$sha1" "$sha256" \
    "$(printf '%s\n' "$control" | base64 -w0)" >> "$WORK/fixes"
  # Same stanza layout as update-index.sh.
  {
    printf 'Package: %s\nVersion: %s\nArchitecture: %s\n' \
      "$(dpkg-deb --field "$deb" Package)" "$(dpkg-deb --field "$deb" Version)" "$(dpkg-deb --field "$deb" Architecture)"
    printf '%s\n' "$control" | grep -v -E '^(Package|Version|Architecture):'
    printf 'Filename: pool/%s/%s\nSize: %s\nMD5sum: %s\nSHA1: %s\nSHA256: %s\n' \
      "$tag" "$file" "$size" "$md5" "$sha1" "$sha256"
  } > "$WORK/stanzas/${tag}__${file}"
done < <(grep '^STALE' "$WORK/drift")

if [[ "$DRY_RUN" == true ]]; then
  echo "Dry run: $(wc -l < "$WORK/fixes") stale asset(s), nothing written."
  exit $(( missing > 0 ))
fi

# Index rows: refresh size, hashes and control for both channels.
tmp=$(mktemp)
awk 'NR==FNR { fix[$1" "$2]=$3" "$4" "$5" "$6" "$7; next }
     { n=split($6,u,"/"); k=u[n-1]" "u[n]
       if (k in fix) { split(fix[k],f," "); $7=f[1]; $8=f[2]; $9=f[3]; $10=f[4]; $11=f[5] }
       print }' "$WORK/fixes" index/packages.tsv > "$tmp"
mv "$tmp" index/packages.tsv

# Frozen legacy suites are not regenerated by update-index.sh: patch stanzas in place.
LEGACY_SUITES=""
for f in dists/*/main/binary-*/Packages; do
  [[ -f "$f" ]] || continue
  tmp=$(mktemp)
  awk -v dir="$WORK/stanzas" 'BEGIN { RS=""; ORS="\n\n" }
    { if (match($0, /(^|\n)Filename: pool\/[^\n]*/)) {
        fn=substr($0, RSTART, RLENGTH); sub(/^\n?Filename: pool\//, "", fn); sub(/\//, "__", fn)
        path=dir "/" fn
        if ((getline line < path) > 0) {
          out=line; while ((getline line < path) > 0) out=out "\n" line; close(path)
          print out; next
        }
      }
      print }' "$f" > "$tmp"
  if cmp -s "$tmp" "$f"; then rm -f "$tmp"; continue; fi
  mv "$tmp" "$f"
  gzip -k -f "$f"; xz -k -f "$f"
  suite=${f#dists/}; suite=${suite%%/*}
  [[ " ${LEGACY_SUITES} " == *" ${suite} "* ]] || LEGACY_SUITES+="${LEGACY_SUITES:+ }${suite}"
  echo "Patched legacy: ${f}"
done

echo "Resynced $(wc -l < "$WORK/fixes") asset(s). Legacy suites to re-sign: ${LEGACY_SUITES:-none}"
[[ -z "${GITHUB_OUTPUT:-}" ]] || echo "legacy_suites=${LEGACY_SUITES}" >> "$GITHUB_OUTPUT"
exit $(( missing > 0 ))
